# Generated by Django 3.0.7 on 2020-07-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200714_2324'),
        ('goals', '0002_auto_20200727_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='books',
            field=models.ManyToManyField(to='books.Books'),
        ),
    ]
