# Generated by Django 3.0.7 on 2020-06-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercollections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collecions',
            options={'verbose_name': 'Collections', 'verbose_name_plural': 'Collections'},
        ),
    ]
