# Generated by Django 3.0.7 on 2020-06-30 14:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_auto_20200629_0150'),
        ('usercollections', '0002_auto_20200701_0015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='collecions',
            new_name='Collection',
        ),
    ]
