# Generated by Django 3.0.7 on 2020-06-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercollections', '0003_auto_20200701_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
