# Generated by Django 3.0.7 on 2020-07-08 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200629_0150'),
        ('usercollections', '0004_auto_20200701_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booksadd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Books')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercollections.Collection')),
            ],
        ),
    ]
