# Generated by Django 3.0.7 on 2020-07-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercollections', '0005_booksadd'),
    ]

    operations = [
    ]
