# Generated by Django 3.0.7 on 2020-06-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='authors',
        ),
        migrations.AddField(
            model_name='books',
            name='authors',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.RemoveField(
            model_name='books',
            name='genres',
        ),
        migrations.AddField(
            model_name='books',
            name='genres',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
