# Generated by Django 3.0.7 on 2020-07-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200629_0150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-ISBN']},
        ),
    ]
